sonar.projectKey=sonarqube-owasp-node-demo
sonar.projectName=SonarQube OWASP Node Demo
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=node_modules/**,reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info